POST http://localhost:3000/register/
Content-Type: application/json 

{
    "username":"Joel",
    "name":"Joel prakash",
    "password":"123456",
    "gender":"Male"
}
###

POST http://localhost:3000/login/
Content-Type: application/json 

{
    "username":"Joel",
    "password":"123456"
}
###

GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZWwiLCJpYXQiOjE2NTE1NTgwNjl9.6of5mfFW0bnkzqyY-qF5WxgkSBk7MlJV6SHkRldBXxc
###

GET http://localhost:3000/user/following/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZWwiLCJpYXQiOjE2NTE1NTgwNjl9.6of5mfFW0bnkzqyY-qF5WxgkSBk7MlJV6SHkRldBXxc
###

GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZWwiLCJpYXQiOjE2NTE1NTgwNjl9.6of5mfFW0bnkzqyY-qF5WxgkSBk7MlJV6SHkRldBXxc
###

GET http://localhost:3000/tweets/2/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZWwiLCJpYXQiOjE2NTE1NTgwNjl9.6of5mfFW0bnkzqyY-qF5WxgkSBk7MlJV6SHkRldBXxc
###

GET http://localhost:3000/tweets/2/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZWwiLCJpYXQiOjE2NTE1NTgwNjl9.6of5mfFW0bnkzqyY-qF5WxgkSBk7MlJV6SHkRldBXxc
###

GET http://localhost:3000/tweets/2/replies/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZWwiLCJpYXQiOjE2NTE1NTgwNjl9.6of5mfFW0bnkzqyY-qF5WxgkSBk7MlJV6SHkRldBXxc
###

GET http://localhost:3000/user/tweets/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZWwiLCJpYXQiOjE2NTE1NTgwNjl9.6of5mfFW0bnkzqyY-qF5WxgkSBk7MlJV6SHkRldBXxc
###